name: Trigger Child Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  # trigger-child-1:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Trigger Child 1 Workflow
  #       uses: peter-evans/repository-dispatch@v3
  #       with:
  #         repository: srikanthhg/child
  #         event-type: trigger-workflow
  #         token: ${{ secrets.GH_PATS }}
  # child-status:
  #   runs-on: ubuntu-latest
  #   needs: trigger-child-1
  #   steps:
  #   - name: Check Status of Child 1 Workflow
  #     run: |
  #       child_status=$(curl -L \
  #         -H "Accept: application/vnd.github+json" \
  #         -H "Authorization: Bearer ${{ secrets.GH_PATS }}" \
  #         -H "X-GitHub-Api-Version: 2022-11-28" \
  #        https://api.github.com/repos/srikanthhg/child/actions/runs | jq '.workflow_runs | sort_by(.created_at) | last | {id: .id, name: .name, status: .status, conclusion: .conclusion, created_at: .created_at}')
  #        echo "Child Status: $child_status"

  dir:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - name: created dirs and files
      run: |
       mkdir -p hello
       mkdir -p hello1
    - name: testing
      run: ls
  test:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    needs: dir
    steps:
    - name: testing dir and files
      run: ls
  # cleanup:
  #   runs-on: self-hosted
  #   # runs-on: ubuntu-latest
  #   needs: [dir, test]
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #     with:
  #       clean: true







# name: Parent Workflow

# on:
#   push:
#     branches:
#       - main

# jobs:
#   trigger-child-workflows:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         child-repo: [repo-b, repo-c]  # List of child repositories

#     steps:
#       - name: Trigger child workflow in Repo B or Repo C
#         run: |
#           curl -X POST \
#             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
#             -d '{"event_type": "trigger-child-workflow", "client_payload": {"repo": "${{ matrix.child-repo }}"}}' \
#             https://api.github.com/repos/${{ matrix.child-repo }}/dispatches

