name: Trigger Child Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger-child-1:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Child 1 Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: srikanthhg/child
          event-type: trigger-workflow
          token: ${{ secrets.GH_PATS }}
  child-status:
    runs-on: ubuntu-latest
    steps:
    - name: Check Status of Child 1 Workflow
      run: |
        curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PATS }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
         child_status=$(https://api.github.com/repos/srikanthhg/child/actions/runs --jq '.workflow_runs[0].status')
         echo "Child Status: $child_status"
